"""Lista central das extensoes carregadas pelo bot."""

COG_EXTENSIONS = (
    "cogs.setup",
    "cogs.sistema",
    "cogs.membros",
    "cogs.setup_set",
    "cogs.farm",
    "cogs.ausencia",
    "cogs.acao",
    "cogs.anuncio",
    "cogs.encomenda",
    "cogs.paineis",
    "cogs.setup_paineis",
    "cogs.lideranca",
    "cogs.setup_lideranca",
    "cogs.adv",
    "cogs.colete",
    "cogs.dashboard",
    "cogs.farm_painel",
    "cogs.farm_tickets",
    "cogs.ranking_painel",
    "cogs.hierarquia",
    "cogs.acao_painel",
    "cogs.radio",
    "cogs.bau",
    "cogs.mod",
    "cogs.recolhimento",
    "cogs.bau_gerentes",
    "cogs.disparo",
)
